_filename: 'tvshow'
tvshow:
  - title: '{title}'
  - sorttitle: '{title}'
  - season: '-1'
  - episode: '-1'
  - year:
      converter:
        data_type: 'date'
        input_format: '%Y%m%d'
        output_format: '%Y'
      value: '{upload_date}'
  - premiered:
      converter:
        data_type: 'date'
        input_format: '%Y%m%d'
        output_format: '%Y-%m-%d'
      value: '{upload_date}'
  - displayorder: 'aired'
  - outline: '{description}'
  - plot: '{description}'
  - genre: 'Nebula'
  - uniqueid:
      attrs:
        default: 'true'
        type: 'nebula'
      value: '{id}'
  - nebulaid: '{id}'
