episodedetails:
  - title: '{title}'
  - showtitle: '{uploader}'
  - uniqueid:
      attrs:
        default: 'true'
        type: 'youtube'
      value: '{id}'
  - plot: '{description}'
  - premiered:
      converter:
        data_type: 'date'
        input_format: '%Y%m%d'
        output_format: '%Y-%m-%d'
      value: '{upload_date}'
